#!/bin/bash

# BlockCats Railway Manual Deployment Script
echo "🚂 BlockCats Railway Manual Deployment"
echo "===================================="

echo "📋 Since Railway CLI requires interactive prompts, here's what to do:"
echo ""

echo "🚀 STEP 1: Add Backend Service"
echo "=============================="
echo "Run this command in your terminal:"
echo "railway add"
echo ""
echo "When prompted, select:"
echo "  - Service type: Backend/API"
echo "  - Template: Docker"
echo ""

echo "🚀 STEP 2: Set Backend Environment Variables"
echo "==========================================="
echo "Run these commands one by one:"
echo ""
echo "railway variables --set 'NODE_ENV=production'"
echo "railway variables --set 'PORT=3000'"
echo "railway variables --set 'POLYGON_AMOY_RPC_URL=https://rpc-amoy.polygon.technology'"
echo "railway variables --set 'DEPLOYER_PRIVATE_KEY=0x7acc9a5d79c4e13f1e6e47362d9de7df50289bb57a72ffb0c7e0b32c16aaaaac'"
echo "railway variables --set 'ETHERSCAN_API_KEY=TMSAH6XD1FYN7ENYPAZGAV8WXKZ9W1H23X'"
echo "railway variables --set 'CONTRACT_ADDRESS=0xC585c0ee9eDe4f35dbA97513570f9351d2B634E9'"
echo ""

echo "🚀 STEP 3: Deploy Backend"
echo "========================"
echo "railway up"
echo ""

echo "🚀 STEP 4: Get Backend URL"
echo "========================="
echo "railway domain"
echo "(Save this URL for the Minecraft service)"
echo ""

echo "🎮 STEP 5: Add Minecraft Service"
echo "==============================="
echo "railway add"
echo ""
echo "When prompted, select:"
echo "  - Service type: Minecraft/Game Server"
echo "  - Template: Docker"
echo ""

echo "🎮 STEP 6: Set Minecraft Environment Variables"
echo "============================================="
echo "railway variables --set 'JAVA_OPTS=-Xmx2G -Xms1G'"
echo "railway variables --set 'SERVER_PORT=25565'"
echo "railway variables --set 'API_URL=https://YOUR_BACKEND_URL.railway.app'"
echo "(Replace YOUR_BACKEND_URL with the actual URL from Step 4)"
echo ""

echo "🎮 STEP 7: Deploy Minecraft"
echo "==========================="
echo "railway up"
echo ""

echo "🎮 STEP 8: Get Minecraft URL"
echo "============================"
echo "railway domain"
echo ""

echo "🧪 STEP 9: Test Your Deployment"
echo "==============================="
echo "Test backend API:"
echo "curl https://YOUR_BACKEND_URL.railway.app/api/minecraft/spawn"
echo ""
echo "Connect to Minecraft:"
echo "Server Address: YOUR_MINECRAFT_URL.railway.app:25565"
echo "Server Name: BlockCats Railway Server"
echo ""

echo "🎯 Your BlockCats server will be live on Railway! 🐱⚔️"
