#!/bin/bash

# BlockCats Railway Docker Hub Deployment
echo "🚂 BlockCats Railway Docker Hub Deployment"
echo "========================================="

echo "📋 Alternative approach using Railway Dashboard:"
echo ""

echo "🌐 STEP 1: Go to Railway Dashboard"
echo "================================="
echo "1. Visit: https://railway.app/dashboard"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose your 'maximillian/BlockCats' repository"
echo ""

echo "🚀 STEP 2: Deploy Backend Service"
echo "================================="
echo "1. Click 'Add Service'"
echo "2. Select 'Deploy from Docker Hub'"
echo "3. Image: wapiozi/blockcats-backend:latest"
echo "4. Service Name: blockcats-backend"
echo "5. Set Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=3000"
echo "   POLYGON_AMOY_RPC_URL=https://rpc-amoy.polygon.technology"
echo "   DEPLOYER_PRIVATE_KEY=0x7acc9a5d79c4e13f1e6e47362d9de7df50289bb57a72ffb0c7e0b32c16aaaaac"
echo "   ETHERSCAN_API_KEY=TMSAH6XD1FYN7ENYPAZGAV8WXKZ9W1H23X"
echo "   CONTRACT_ADDRESS=0xC585c0ee9eDe4f35dbA97513570f9351d2B634E9"
echo "6. Click 'Deploy'"
echo ""

echo "🎮 STEP 3: Deploy Minecraft Service"
echo "==================================="
echo "1. Click 'Add Service'"
echo "2. Select 'Deploy from Docker Hub'"
echo "3. Image: wapiozi/blockcats-minecraft:latest"
echo "4. Service Name: blockcats-minecraft"
echo "5. Set Environment Variables:"
echo "   JAVA_OPTS=-Xmx2G -Xms1G"
echo "   SERVER_PORT=25565"
echo "   API_URL=https://blockcats-backend-production.up.railway.app"
echo "6. Click 'Deploy'"
echo ""

echo "🌐 STEP 4: Get Your URLs"
echo "======================="
echo "After deployment, you'll get:"
echo "- Backend API: https://blockcats-backend-production.up.railway.app"
echo "- Minecraft Server: blockcats-minecraft-production.up.railway.app:25565"
echo ""

echo "🧪 STEP 5: Test Your Deployment"
echo "==============================="
echo "Test backend API:"
echo "curl https://blockcats-backend-production.up.railway.app/api/minecraft/spawn"
echo ""
echo "Connect to Minecraft:"
echo "Server Address: blockcats-minecraft-production.up.railway.app:25565"
echo "Server Name: BlockCats Railway Server"
echo ""

echo "🎯 This is the EASIEST method - no CLI required! 🐱⚔️"
