#!/bin/bash

# BlockCats Railway Interactive Deployment
echo "🚂 BlockCats Railway Interactive Deployment"
echo "========================================"

echo "📋 This script will guide you through Railway deployment"
echo ""

# Check if Railway is linked
echo "🔍 Checking Railway project status..."
railway status

echo ""
echo "🚀 Step 1: Deploy Backend Service"
echo "================================="
echo "Run these commands in your terminal:"
echo ""
echo "1. Add backend service:"
echo "   railway add"
echo "   (Select 'Backend' or 'API' when prompted)"
echo ""
echo "2. Set environment variables:"
echo "   railway variables --set 'NODE_ENV=production'"
echo "   railway variables --set 'PORT=3000'"
echo "   railway variables --set 'POLYGON_AMOY_RPC_URL=https://rpc-amoy.polygon.technology'"
echo "   railway variables --set 'DEPLOYER_PRIVATE_KEY=0x7acc9a5d79c4e13f1e6e47362d9de7df50289bb57a72ffb0c7e0b32c16aaaaac'"
echo "   railway variables --set 'ETHERSCAN_API_KEY=TMSAH6XD1FYN7ENYPAZGAV8WXKZ9W1H23X'"
echo "   railway variables --set 'CONTRACT_ADDRESS=0xC585c0ee9eDe4f35dbA97513570f9351d2B634E9'"
echo ""
echo "3. Deploy backend:"
echo "   railway up"
echo ""
echo "4. Get backend URL:"
echo "   railway domain"
echo ""

echo "🎮 Step 2: Deploy Minecraft Service"
echo "=================================="
echo "Run these commands in your terminal:"
echo ""
echo "1. Add Minecraft service:"
echo "   railway add"
echo "   (Select 'Minecraft' or 'Game Server' when prompted)"
echo ""
echo "2. Set environment variables:"
echo "   railway variables --set 'JAVA_OPTS=-Xmx2G -Xms1G'"
echo "   railway variables --set 'SERVER_PORT=25565'"
echo "   railway variables --set 'API_URL=https://your-backend-url.railway.app'"
echo "   (Replace 'your-backend-url' with the actual backend URL from step 1)"
echo ""
echo "3. Deploy Minecraft:"
echo "   railway up"
echo ""
echo "4. Get Minecraft URL:"
echo "   railway domain"
echo ""

echo "🌐 Step 3: Test Your Deployment"
echo "==============================="
echo "After both services are deployed:"
echo ""
echo "1. Test backend API:"
echo "   curl https://your-backend-url.railway.app/api/minecraft/spawn"
echo ""
echo "2. Connect to Minecraft:"
echo "   Server Address: your-minecraft-url.railway.app:25565"
echo "   Server Name: BlockCats Railway Server"
echo ""

echo "🎯 Your BlockCats server will be live on Railway! 🐱⚔️"
